# Generated by Selenium IDE
import os
import subprocess
import threading
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait


def prev_cookies(cookies):
    for cookie in cookies:
        print(cookie["name"], cookie["value"])


if __name__ == '__main__':
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    prefs = {"profile.managed_default_content_settings.images": 2}

    caps = DesiredCapabilities().CHROME
    # caps["pageLoadStrategy"] = "normal"  #  Waits for full page load
    caps["pageLoadStrategy"] = "none"

    options.add_experimental_option("prefs", prefs)
    chromeDriver = webdriver.Chrome(
        executable_path="../lib/chromedriver.exe", options=options, desired_capabilities=caps)
    chromeDriver.get("https://www.wegame.com.cn/")
    WebDriverWait(chromeDriver, 10).until(
        expected_conditions.presence_of_element_located((By.CLASS_NAME, 'widget-header-login-btn')))
    chromeDriver.find_element_by_class_name("widget-header-login-btn").click()

    iframe = chromeDriver.find_elements_by_tag_name("iframe")[0]
    chromeDriver.switch_to.frame(iframe)

    WebDriverWait(chromeDriver, 10).until(
        expected_conditions.presence_of_element_located((By.ID, 'switcher_plogin')))
    chromeDriver.implicitly_wait(1)
    chromeDriver.find_element(By.ID, "switcher_plogin").click()
    chromeDriver.find_element(By.ID, "u").send_keys("")
    # 输入密码
    chromeDriver.find_element(By.ID, "p").send_keys("")
    # 发送登录请求
    chromeDriver.find_element(By.ID, "login_button").click()
    chromeDriver.switch_to.default_content()
    WebDriverWait(chromeDriver, 10).until(
        expected_conditions.invisibility_of_element_located((By.ID, "login")))
    cookies = chromeDriver.get_cookies()
    prev_cookies(cookies)




