name: cover
on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./requirements.txt