name: cover
on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rushd
          path: ./requirements.txt